spring:
  datasource:
    url: jdbc:h2:file:./data/database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database: h2
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
      springframework:
        security: DEBUG
    tech:
      bjut:
        su:
          appeal: DEBUG
app:
  store:
    path: ./data/uploads
  frontend: http://localhost:5173
