debug: true
spring:
  datasource:
    url: jdbc:h2:file:./data/database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
logging:
  level:
    tech:
      bjut:
        su:
          appeal: TRACE
app:
  store:
    path: ./data/uploads
  frontend: http://localhost:5173
