spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database: h2
  h2:
    console:
      enabled: false
