spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    database: h2
  h2:
    console:
      enabled: false
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
    tech:
      bjut:
        su:
          appeal: DEBUG
app:
  auth:
    admin:
      - admin
  store:
    path: ./data/uploads
  frontend: http://localhost:5173
