spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database: h2
  h2:
    console:
      enabled: false
