spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database: h2
  h2:
    console:
      enabled: false
app:
  store:
    path: ./data/uploads
  frontend: http://localhost:5173
